services:
  postgres:
    image: postgres:alpine
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_volume:/var/lib/postresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_volume:
    driver: local
  
